FROM postgres:latest AS build
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/Deniable-IM/denim.git

FROM postgres:latest AS production
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=signal_db

WORKDIR /docker-entrypoint-initdb.d
COPY --from=build /denim/server/database/init.sql .

CMD ["docker-entrypoint.sh", "postgres"]
