package Messagemaker

var nonsenseQuotes = []string{
	"The pineapple doesnt negotiate with Thursdays",
	"Quantum waffles taste better with invisible syrup",
	"Never trust a duck wearing suspenders",
	"Yesterdays spoon forgot its destiny",
	"Banana clocks tick in reverse under lunar influence",
	"Toaster dreams are valid but only on leap years",
	"A whispering cactus solves no debates",
	"Fold the universe neatly before bedtime",
	"My shoelaces have existential crises every solstice",
	"Colorless green unicorns jump lazily over bewildered shadows",
	"Theres no such thing as a polite sneeze in hyperspace",
	"Carrots cant vote but they do gossip",
	"Trains dont whistle in underwater libraries",
	"Beware the salad that reads poetry aloud",
	"Gravity is just Earth giving you a hug aggressively",
	"Happiness is a rubber duck in a desert storm",
	"Even the clouds forgot how to spell muffin",
	"The moon is just a flashlight with commitment issues",
	"Please dont pet the lava",
	"Every sock has a secret vendetta",
	"You cant juggle jellyfish with broken metaphors",
	"The alphabet has 26 regrets",
	"Chronological spaghetti bends toward entropy",
	"Waffles are just pancakes with a better lawyer",
	"Silence is golden but duct tape is silver and stickier",
	"Zebras dream in barcode",
	"I saw a tree whisper stock advice to a pigeon",
	"When in doubt blame the algorithmic ferret",
	"A whisper of nonsense still tickles the cosmos",
	"Cheese metaphysics are banned after 3PM",
	"My calculator hums lullabies during tax season",
	"The wind owes me a favor and three compliments",
	"Never microwave sadness on high",
	"Cabbages shouldnt do stand up comedy near volcanoes",
	"The ceiling fan is conspiring with the shadows",
	"To err is human to moo is bovine",
	"Socks are just foot prisons with colorful propaganda",
	"Unicorn taxes are outrageously sparkly this quarter",
	"Ink prefers chaos over coherence",
	"I communicate only in semaphore and marinara sauce",
	"The password is always kumquat",
	"Time travelers hate spoilers especially their own",
	"That was before the great jellybean uprising of 03",
	"Logic took a vacation and left irony in charge",
	"If frogs could drive traffic laws would taste minty",
	"Trust no gnome after midnight",
	"My dreams are sponsored by sentient muffins",
	"The rainbow called in sick today",
	"Dont mix metaphors unless they consent",
	"Giraffes hold the secrets to cosmic WiFi",
	"Entropy the universes way of shrugging",
	"Even paradoxes need a nap sometimes",
	"Reality is just a badly written improv sketch",
	"The lion does not concern itself with traffic laws",
	"Responding is just another way of starting conversations",
	"This one is short",
	"Herro Sorrid Snake",
	"You want make save",
	"Ancient Chinese proverb for you",
	"Confucius say",
	"Man run in front car gets tired",
	"Man run behind car get exhausted",
	"The spy will get spied on eventually",
	"The fact that Large Language Models can sound like middle managers does not make them intelligent but proves middle managers are not",
	"Never trust spaghetti that hums",
	"I once rode a flamingo through downtown Atlantis during rush hour traffic while juggling pineapples and shouting about taxes",
	"Banana hats are optional for this reality",
	"Please do not interrogate the soup",
	"The hedgehog council meets on Tuesdays unless the moon frowns",
	"Octopuses cannot be trusted near fax machines especially if the jellybeans are watching with opera glasses",
	"My bathtub thinks it is a spaceship and frankly I support its dreams",
	"Toasters never forget but they do forgive waffles after mediation",
	"Socks fear Tuesdays more than clowns fear rectangles",
	"The pudding union has demanded equal spoons and marshmallow breaks",
	"My houseplant recently acquired a law degree and insists on being called Counselor Fern",
	"Do not taunt the mayonnaise if it is humming the national anthem backwards",
	"Lunch happened in reverse and now I speak fluent origami",
	"Cabbage cant vote but it files taxes on time",
	"If you find a lizard wearing spectacles ask it about the great pancake betrayal",
	"Chair conspiracy theory number eight involves bees and jazz music",
	"Frogs wear invisible suspenders when time travel becomes fashionable",
	"There is a goose in my filing cabinet whispering tax advice to my stapler",
	"Jellyfish can drive if you do not believe in geometry",
	"Donuts have dreams too especially the powdered ones",
	"My wristwatch thinks I am late for a meeting with destiny and three raccoons",
	"Whales hum sea shanties about lost pizza",
	"Balloons know your secrets but only tell on windy days",
	"Toast told me to live my truth and also to invest in bean futures",
	"Umbrellas are just inverted parachutes with commitment issues",
	"Cats invented algebra during the muffin wars of 1812",
	"I folded my anxiety into a paper crane and now it squawks at 3 AM",
	"Yes the refrigerator dances when the lights go off and it prefers salsa",
	"Gravity took a day off and now all the chairs are hovering in defiance",
	"This sentence contains more whimsy than legally allowed in seven states",
}

func GetQuoteByIndexSafe(index int) string {
	return nonsenseQuotes[(index % len(nonsenseQuotes))]
}
